#!/bin/bash
# Ensures resume npm package is installed
resume --version

#Install the resume themes
npm install jsonresume-theme-onepage
npm install jsonresume-theme-kendall

#Export the different resumes
resume export simple_resume.pdf --theme onepage
resume export resume.pdf --theme kendall